# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

component("browser") {
  output_name = "tab_informer_browser"
  defines = [ "IS_TAB_INFORMER_BROWSER_IMPL" ]

  sources = [
    "tab_informer_service.cc",
    "tab_informer_service.h",
  ]

  deps = [
    "//base",
    "//components/keyed_service/core",
    "//content/public/browser",
  ]

  public_deps = [ "//brave/components/tab_informer/common:mojom" ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "tab_informer_service_unittest.cc" ]
  deps = [
    ":browser",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}
