# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# based on //ui/webui/resources/js/BUILD.gn

import("//ui/webui/resources/tools/build_webui.gni")

include_polymer = !is_android && !is_ios

build_webui("build") {
  grd_prefix = "webui_js"

  non_web_component_files = [
  ]

  if (include_polymer) {
    non_web_component_files += [
      "brave_browser_command/brave_browser_command_proxy.ts",
    ]
  }

  mojo_files_deps = [ ]
  mojo_files = [ ]

  if (include_polymer) {
    mojo_files_deps += [ "./brave_browser_command:mojo_bindings_ts__generator" ]
    mojo_files += [ "$root_gen_dir/brave/ui/webui/resources/js/brave_browser_command/brave_browser_command.mojom-webui.ts" ]
  }

  ts_out_dir = "$root_gen_dir/brave/ui/webui/resources/tsc/js"
  ts_composite = true
  ts_deps = [
    "//ui/webui/resources/js:build_ts",
    "//ui/webui/resources/mojo:build_ts",
  ]
  ts_definitions = [
    "//tools/typescript/definitions/chrome_send.d.ts",
    "//tools/typescript/definitions/chrome_timeticks.d.ts",
  ]
  webui_context_type = "relative"
  generate_grdp = true
  grd_resource_path_prefix = rebase_path(".", "//brave/ui/webui/resources")
}
